### ISSUE TITLE
annotation script parsing error

### ISSUE THREAD

**Issue by ksahlin** [ydLiu-HIT/deSALT#9]
Hi,

I get the following error when running the `src/Annotation_Load.py` script.

```
Traceback (most recent call last):
  File "/galaxy/home/ksahlin/prefix/source/deSALT/src/Annotation_Load.py", line 236, in <module>
    transcripts = Load_Annotation_From_GTF(gffpath, bedpath)
  File "/galaxy/home/ksahlin/prefix/source/deSALT/src/Annotation_Load.py", line 167, in Load_Annotation_From_GTF
    if elements[2] == '.':
IndexError: list index out of range
```

Head of the gtf file looks like this:

```
##description: evidence-based annotation of the human genome (GRCh38), version 31 (Ensembl 97)
##provider: GENCODE
##contact: gencode-help@ebi.ac.uk
##format: gtf
##date: 2019-06-27
chr1	HAVANA	gene	11869	14409	.	+	.	gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37102"; havana_gene "OTTHUMG00000000961.2";
chr1	HAVANA	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "lncRNA"; transcript_name "DDX11L1-202"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1	HAVANA	exon	11869	12227	.	+	.	gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "lncRNA"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1	HAVANA	exon	12613	12721	.	+	.	gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "lncRNA"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
chr1	HAVANA	exon	13221	14409	.	+	.	gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "lncRNA"; transcript_name "DDX11L1-202"; exon_number 3; exon_id "ENSE00002312635.1"; level 2; transcript_support_level "1"; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
```

May I perhaps suggest using the [gffutils](https://pythonhosted.org/gffutils/) module to read in and transform the gtf/gff? In the meantime, is there a quick fix?

Best regards,
Kristoffer

**Comment by ksahlin** [comment]
A quick fix seems to be to insert:
```
        if line[0] == '#':
            continue
```
on line 164.

**Comment by ydLiu-HIT** [comment]
Hi ksahlin:

Thank you for giving this question. Your quick fix is right. 
When I get an annotation file, I first transfer the file to GTF format by gffread, the output file doesn't contain the header. So I didn't process the headers.
I will try gffutils and put a new version if necessary.
Thank you very much.
